In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
digits = load_digits()


In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [16]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [17]:
for train_index , test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print( train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [22]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [24]:
from sklearn.linear_model import LogisticRegression
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

C:\Users\bhuta\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9703703703703703

In [25]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
print("SVC",get_score(SVC(),x_train,x_test,y_train,y_test))
print("Random Forest Classifier",get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))

SVC 0.9796296296296296
Random Forest Classifier 0.975925925925926


# THIS IS FOR UNDERSTANDING PURPOSES

In [32]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits = 3)
scores_l = []
scores_svc = []
scores_rf = []
for train_index , test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test = digits.data[train_index], digits.data[test_index] ,digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    scores_svc.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),x_train,x_test,y_train,y_test))

C:\Users\bhuta\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\bhuta\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [28]:
scores_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [29]:
scores_svc

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [30]:
scores_rf

[0.9398998330550918, 0.9582637729549248, 0.9282136894824707]

# CROSSVAL Method Built-in Method

In [34]:
from sklearn.model_selection import cross_val_score


In [41]:
scores_l = cross_val_score(LogisticRegression(),digits.data,digits.target)
print(np.average(scores_l))

C:\Users\bhuta\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\bhuta\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

0.9137650882079852


C:\Users\bhuta\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [40]:
scores_svc = cross_val_score(SVC(),digits.data,digits.target)
print(np.average(scores_svc))

0.9632838130609718


In [39]:
scores_rf = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)
print(np.average(scores_rf))

0.927116991643454
